### ISSUE TITLE
Add an explicit check of the notebook kernel.

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab#293]
## User stories

As developers, we would like to guarantee that Jupyter notebooks (that are available within an app) can still work if the python kernel changes.

For example, recently we had to place the python kernel in a separate Conda environment (see https://github.com/aiidalab/aiidalab-docker-stack/pull/254). That requires an explicit selection of a new kernel. This should be taken care of by the platform.

## Known issues

We don't have a clear definition of the available notebooks within an app. That means we need to check all the notebooks.

## Tasks

- [ ] Understand how to store the default kernel used for the AiiDAlab apps.
- [ ] Add an automatic check of all the jupyter notebooks within an app.
- [ ] Possibly, implement an automated migration to the new default kernel.

**Comment by yakutovicha** [comment]
@csadorf, should we close this issue since we agreed to have aiida in the base kernel?

**Comment by csadorf** [comment]
> @csadorf, should we close this issue since we agreed to have aiida in the base kernel?

Yes.
